# Generated by Django 3.1.5 on 2021-07-24 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlook_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('cv', models.FileField(blank=True, null=True, upload_to='CVs/')),
                ('applicant_experties', models.ManyToManyField(blank=True, to='outlook_app.Experties')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlook_app.job')),
            ],
            options={
                'unique_together': {('email', 'job')},
            },
        ),
    ]
