# Generated by Django 3.1.5 on 2021-09-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook_app', '0003_auto_20210905_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantform',
            name='experience',
            field=models.SmallIntegerField(choices=[(0, 'Undergraduate'), (1, '0-1 Year'), (2, '1-3 Years'), (3, '3-5 Years'), (4, '5+ Years')], default=1),
        ),
    ]
