# Generated by Django 3.2.6 on 2022-01-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook_app', '0004_applicantform_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantform',
            name='recommendadtion',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='applicantform',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicantform',
            name='score',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
