# Generated by Django 3.2.6 on 2022-01-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook_app', '0005_auto_20220111_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantform',
            name='education',
            field=models.SmallIntegerField(choices=[(0, 'Undergraduate'), (1, 'Bachelors'), (2, 'Masters'), (3, 'PhD')], default=0),
        ),
        migrations.AlterField(
            model_name='applicantform',
            name='experience',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='applicantform',
            name='score',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
    ]
