# Generated by Django 4.0.2 on 2022-02-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook_app', '0009_job_spreadsheetname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experties',
            name='experties',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
